name: Cache Swift
on: push
jobs:
  cache-swift:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6

      - uses: swift-actions/setup-swift@v3
        with:
          swift-version: "6.2.4"

      - name: Cache Swift Package Manager
        # actions/cache/save : キャッシュの保存だけを行う
        # actions/cache/restore : キャッシュの復元だけ行う
        # キャッシュを保存するワークフローを1つだけ実装し、他のワークフローで復元だけを行う場合などに利用可能
        uses: actions/cache@v5
        with:
          key: ${{ runner.os }}-swiftpm-${{ hashFiles('Package.resolved') }}
          path: |
            .build
            .swiftpm
          restore-keys: |
            ${{ runner.os }}-swiftpm-
    
      - name: Build
        run: swift build