name: Contexts
on: push
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.actor }}" # github コンテキストの参照
      - run: echo "${{ github.run_id }}" # ワークフローの実行ID
      - run: echo "${{ github.head_ref }}" # プルリクエストのソースブランチ
      - run: echo "${{ github.workspace }}" # ステップのワーキングディレクトリ
      - run: echo "${{ github.repository }}" # リポジトリ名（octocat/hello-worldのような値）
      - run: echo "${{ github.repository_owner }}" # リポジトリのオーナー名（octocatのような値）
      - run: echo "${{ github.action }}"
      - run: echo "${{ github.action_path }}"
      - run: echo "${{ github.action_ref }}"
      - run: echo "${{ github.action_repository }}"
      - run: echo "${{ github.action_status }}"
      - run: echo "${{ github.actor_id }}"
      - run: echo "${{ github.api_url }}"
      - run: echo "${{ github.base_ref }}"
      - run: echo "${{ github.event_name }}"
      - run: echo "${{ github.graphql_url }}"
      - run: echo "${{ github.job }}"
      - run: echo "${{ github.path }}"
      - run: echo "${{ github.ref }}"
      - run: echo "${{ github.ref_name }}"
      - run: echo "${{ github.ref_protected }}"
      - run: echo "${{ github.ref_type }}"
      - run: echo "${{ github.repository_id }}"
      - run: echo "${{ github.repository_owner_id }}"
      - run: echo "${{ github.repositoryUrl }}"
      - run: echo "${{ github.retention_days }}"
      - run: echo "${{ github.run_number }}"
      - run: echo "${{ github.run_attempt }}"
      - run: echo "${{ github.server_url }}"
      - run: echo "${{ github.sha }}"
      - run: echo "${{ github.triggering_actor }}"
      - run: echo "${{ github.workflow }}"
      - run: echo "${{ github.workflow_ref }}"
      - run: echo "${{ github.workflow_sha }}"
      - run: echo "${{ github.event.pull_request.title }}"