name: Test
on:
   pull_request:
      paths: # 指定したファイルパスのみ
        - "*.swift"
        - "**/*.swift"
      # paths-ignore: # 指定したファイルパス以外
      # branches: # 指定したブランチのみ
      # branches-ignore: # 指定したブランチ以外
      # tags: # 指定したGitタグのみ
      # tags-ignore: # 指定したGitタグ以外
   # issues: # アクティビティタイプが省略されると、Issueの全イベントがトリガーになる
     # types: [opened, edited] # アクティビティタイプを指定, typesへ指定可能な値はイベントによって異なる
     # pull-requests: # Pull Requestでアクティビティイベントを省略した時のtypeは以下
        # type: [opened, synchronize, reopened]
jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6 # ステップ1: チェックアウト

      - uses: swift-actions/setup-swift@v3 # ステップ2: 言語セットアップ
        with:
          swift-version: "6.2.4"

      - name: Swift Version
        run: swift --version # バージョン確認

      - name: Build
        run: swift build # ビルドの実行

      - name: Run Test
        run: swift test --parallel  # ステップ3: テストの実行