name: Test
on:
   pull_request:
      paths:
        - "*.swift"
        - "**/*.swift"
jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4 # ステップ1: チェックアウト

      - uses: swift-actions/setup-swift@v3 # ステップ2: 言語セットアップ
        with:
          swift-version: "6.2.4"

      - name: Swift Version
        run: swift --version # バージョン確認

      - name: Build
        run: swift build # ビルドの実行

      - name: Run Test
        run: swift test --parallel  # ステップ3: テストの実行